#!/usr/bin/python3
import argparse
import sys
from sys import stdin, stdout, stderr
import re
import statistics

def get_data():
    try:
        data = "".join([i for i in stdin])
        data = re.split('[,\n\s]', data)
        data = list(filter(None, data))
        try:
            data = [int(i) for i in data]
        except ValueError:
            data = [float(i) for i in data]
        return data
    except ValueError as e:
        stderr.write(f"Invalid input value: {e}\nTry: {sys.argv[0]} --help\n")
        exit(1)



def main():
    parser = argparse.ArgumentParser(
            description="Median will calculate the median value from a provided list.")
    parser.add_argument('-H',
            '--high',help="To get high median of data.",
            action="store_true")
    parser.add_argument('-L',
            '--low',help="To get low median of data.",
            action="store_true")
    parser.add_argument('-V',
            '--verbose',
            help="To get all medians.",
            action="store_true")
    args = parser.parse_args()

    data = get_data()
    ml = statistics.median_low(data)
    me = statistics.median(data)
    mh = statistics.median_high(data)

    if args.verbose:
        stdout.write(f"Low median: {ml} Median: {me} High Median: {mh}\n")
    elif args.low:
        stdout.write(f"{ml}\n")
    elif args.high:
        stdout.write(f"{mh}\n")
    else:
        stdout.write(f"{me}\n")

if __name__ == "__main__":
    main()

