#!/usr/bin/python3
import sys
from sys import stdin, stdout, stderr
import re
import statistics

def get_data():
    try:
        data = "".join([i for i in stdin])
        data = re.split('[,\n\s]', data)
        data = list(filter(None, data))
        try:
            data = [int(i) for i in data]
        except ValueError:
            data = [float(i) for i in data]
        return data
    except ValueError as e:
        stderr.write(f"Invalid input value: {e}\nTry: {sys.argv[0]} --help\n")
        exit(1)



def _help():
    print("""
Median will calculate the median value from a provided list.

Default output with no argument is Median.

[--help]         To get thist message.
[-h | --high]    To get high median of data.
[-l | --low]     To low medianof data.
[-v | --verbose] To get all medians.
            """)
    exit(0)

def main():
    data = get_data()
    ml = statistics.median_low(data)
    me = statistics.median(data)
    mh = statistics.median_high(data)

    if bool(re.search(r'(-v|--verbose)', str(sys.argv))):
        stdout.write(f"Low median: {ml} Median: {me} High Median: {mh}\n")
    elif bool(re.search(r'(-l|--low)', str(sys.argv))):
        stdout.write(f"{ml}\n")
    elif bool(re.search(r'(-h\ |--high)', str(sys.argv))):
        stdout.write(f"{mh}\n")
    elif bool(re.search(r'--help', str(sys.argv))):
        _help()
    else:
        stdout.write(f"{me}\n")

if __name__ == "__main__":
    main()

