#!/usr/bin/awk -f
# Rounds numbers to the closest integer and prints them out on separate lines.
# To append unit specify `round -v unit=<unit>` or just unit as an argument.
BEGIN {
        if (ARGC > 1) {
            arg = ARGV[1];
            delete ARGV[1];
            unit = arg
        }
}

NF == 1 {
        print int($0 + 0.5) unit
}

NF > 1 {
        n = split($0, arr,/(\s|\t|,)/)
        for (i in arr)
             print int(arr[i] + 0.5) unit
}
